name: GDI Deploy 1.0
description: Set version, build and push docker image to github registry for a gdi service.

inputs:
  update-openapi-version:
    description: If the version of an OpenAPI specification should be updated
    required: false
    type: boolean
  openapi-spec-file:
    description: Path to the openapi yml specification file to update, relative to the root of the repository.
    required: false
    type: string
  update-package-json-version:
    description: If the version of package.json should be updated.
    required: false
    type: boolean
  release-tag-name:
    description: The tag that was just released
    required: true
    type: string

runs:
  using: composite
  steps:
    # - name: Dump GitHub context
    #   id: github_context_step
    #   run: echo '${{ toJSON(github) }}'
    #   shell: bash

    # - name: Dump job context
    #   run: echo '${{ toJSON(job) }}'
    #   shell: bash

    # - name: Dump steps context
    #   run: echo '${{ toJSON(steps) }}'
    #   shell: bash

    # - name: Dump runner context
    #   run: echo '${{ toJSON(runner) }}'
    #   shell: bash

    # - name: Dump strategy context
    #   run: echo '${{ toJSON(strategy) }}'
    #   shell: bash

    # - name: Dump matrix context
    #   run: echo '${{ toJSON(matrix) }}'
    #   shell: bash
      -
        name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      -
        name: Set openapi version
        uses: rmeneely/update-yaml@v1
        with:
          infile: ${{ inputs.openapi-spec-file }}
          varlist: info.version=${{ inputs.release-tag-name }}

      - 
        name: Set package.json version
        if: inputs.update-package-version == true
        run: npm version --no-git-tag-version ${{ inputs.release-tag-name }}
        shell: bash
      
      - 
        name: Commit and push
        if: inputs.update-openapi-version == true || inputs.update-package-version == true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "🔖 Set versions to release tag ${{ inputs.release-tag-name }}"
          git push -f origin main
        shell: bash

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Repository Variable to Lowercase
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ghcr.io/${{ steps.string.outputs.lowercase }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger config repo update
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: helsingborg-stad
          repo: ${{ secrets.GDI_GITOPS_CONFIG_REPO }}
          github_token: ${{ secrets.GDI_GITOPS_TOKEN }}
          workflow_file_name: update-config.yml
          inputs: '{"semver": "${{ github.event.release.tag_name }}", "app": "${{ secrets.GDI_GITOPS_APP }}"}'
          wait_workflow: false
          ref: main
